reduce heap allocation
istio/proxy pull request #3222
Opened 2021-03-01 23:31 UTC by mandarjog

Continuation of https://github.com/istio/proxy/pull/2965

2021-03-01 23:33 UTC, mandarjog commented
@bianpengyuan we need to do the same in the istio-extensions repo.

2021-03-01 23:38 UTC, PiotrSikora requested changes

2021-03-01 23:38 UTC, PiotrSikora commented on extensions/BUILD
> +    "-s TOTAL_STACK=5MB",
`TOTAL_STACK=5MB` is the default value, so we might skip it.

2021-03-01 23:38 UTC, PiotrSikora commented on extensions/BUILD
> +    "-s TOTAL_MEMORY=8MB",
`TOTAL_MEMORY` was renamed to `INITIAL_MEMORY` a year ago.

2021-03-01 23:38 UTC, PiotrSikora commented on extensions/BUILD
> +    "--js-library external/proxy_wasm_cpp_sdk/proxy_wasm_intrinsics.js",
Is this needed here?

2021-03-01 23:46 UTC, bianpengyuan commented on extensions/BUILD
> +    "--js-library external/proxy_wasm_cpp_sdk/proxy_wasm_intrinsics.js",
This is not needed.

2021-03-02 01:25 UTC, istio-testing commented
@mandarjog: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-tsan_proxy | 4f718ed8a5d2f1d49d2f8e4071f93260151d0138 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_proxy/3222/test-tsan_proxy/1366558596870967296) | `/test test-tsan_proxy`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-02 02:18 UTC, PiotrSikora commented
/retest

2021-03-02 02:18 UTC, PiotrSikora approved these changes
Thanks!

2021-03-05 02:54 UTC, PiotrSikora commented
@bianpengyuan PTAL

2021-03-05 02:56 UTC, bianpengyuan approved these changes

2021-03-05 03:20 UTC, merged