Makefile: fix shell target to be phony
istio/proxy pull request #3322
Opened 2021-05-03 14:43 UTC by rmstoi

**What this PR does / why we need it**:

This PR makes "shell" target to be phony. This fixes the following issue if there is a file with name shell:

```
$ BUILD_WITH_CONTAINER=1 make shell
make: 'shell' is up to date.
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2021-05-03 14:44 UTC, istio-testing commented
Hi @rmstoi. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fproxy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-03 15:25 UTC, bianpengyuan requested changes
This is automatically copied from common-files repo: https://github.com/istio/common-files/blob/master/files/Makefile#L54, you should change it directly here.

Also I don't think `shell` is really a target available in proxy repo.

2021-05-03 17:58 UTC, rmstoi commented
> This is automatically copied from common-files repo: https://github.com/istio/common-files/blob/master/files/Makefile#L54, you should change it directly here.
> 
> Also I don't think `shell` is really a target available in proxy repo.

Thanks for the info, I can try to make PR to common-files repo.
How often changes from common-files repo are merged?

If I understand correctly `shell` target is available if [BUILD_WITH_CONTAINER=1](https://github.com/istio/proxy/blob/master/Makefile#L33) is set
I've been using `shell` target of istio proxy to get shell access to the build-tools-proxy docker image. As here:

`BUILD_WITH_CONTAINER=1 make shell`

I agree, probably not a conventional approach, nevertheless, good way to learn how the build system works.

2021-05-03 18:14 UTC, bianpengyuan commented
> How often changes from common-files repo are merged?

There is no frequency limit on commit merge to that repo AFAIK..

2021-05-04 10:21 UTC, rmstoi commented
Closing PR since moved to [common-files](https://github.com/istio/common-files/pull/411). Thanks @bianpengyuan

2021-05-04 10:21 UTC, closed without merging